### ISSUE TITLE
undefined method `encoding' for #<Hash:0x000001045ee598>

### ISSUE THREAD

**Issue by langalex** [wildbit/postmark-rails#10]
I'm getting this error when trying to send an attachent like so:

```
mail from: "...",
  to: '...',
  subject: "...",
  postmark_attachments: {
    'Name' => "test.pdf",
    'Content' => Base64.encode64('<pdf content>'),
    'ContentType' => "application/pdf"
  }
```

using postmark-rails 0.4.1, postmark 0.9.6, ActionMailer 3.0.6 and mail 2.2.15. it works with older mail versions (2.2.10).
